_target_: tensorframes.equivectors.equiformer.EquiTransformer
_partial_: true

n_vectors: null
num_scalars: null
num_blocks: 1
hidden_scalars: 16
hidden_vectors: 8
increase_attention_vectors: 8
layer_norm: true