_target_: lloca.equivectors.pelican.PELICANVectors
_partial_: true

n_vectors: null
num_scalars: null

operation: add
nonlinearity: softmax
aggr: sum
fm_norm: false

net:
 _target_: pelican.nets.PELICAN
 _partial_: true

 num_blocks: 1
 hidden_channels: 16
 increase_hidden_channels: 1
 in_rank0: 0
 in_rank1: null
 in_rank2: 1
 out_rank: 1
 out_channels: null
 factorize: false
 activation: gelu
 aggr: mean
