_target_: experiments.amplitudes.wrappers.PELICANWrapper
particle_type: null
network_float64: null

net:
 _target_: pelican.nets.PELICAN

 in_rank0: 0
 in_rank1: null
 in_rank2: 1
 out_rank: 0
 out_channels: 1

 num_blocks: 2
 hidden_channels: 16
 increase_hidden_channels: 1.

 factorize: true
 activation: gelu
 aggr: mean
 compile: true

defaults:
 - lframesnet: identity
