_target_: experiments.tagging.wrappers.ParTWrapper
in_channels: null
out_channels: null
use_amp: false
add_fourmomenta_backbone: false

net:
 _target_: lloca.nn.particletransformer.ParticleTransformer
 _partial_: true
 input_dim: null
 num_classes: null

 attn_reps: 8x0n+2x1n

 use_amp: ${model.use_amp}
 trim: false

 use_pre_activation_pair: false
 pair_input_dim: 4
 cls_block_params:
  dropout: 0
  attn_dropout: 0
  activation_dropout: 0
 version: 1

defaults:
 - lframesnet: identity
