_target_: experiments.tagging.wrappers.ParticleNetWrapper
in_channels: null
out_channels: null
add_fourmomenta_backbone: false

net:
 _target_: lloca.nn.particlenet.ParticleNet
 _partial_: true
 num_classes: null
 conv_params: [[7, [32, 32, 32]], [7, [64, 64, 64]]]
 fc_params: [[128, 0.1]]
 input_dims: null
 hidden_reps_list: ["7x0n", "16x0n+4x1n"]

defaults:
 - lframesnet: identity
